SET serveroutput ON;

DECLARE
  ncount NUMBER;
BEGIN
  SELECT COUNT(1) INTO ncount FROM all_users WHERE username = 'WEBADMIN';

  IF ncount > 0 THEN
    DBMS_OUTPUT.PUT_LINE('USER WEBADMIN ALREADY EXISTS');
  ELSE
    
    EXECUTE IMMEDIATE 'CREATE USER webAdmin IDENTIFIED BY GCQiRbpWBk1q';
    --EXECUTE IMMEDIATE 'GRANT DROP ROLE TO webAdmin';
    

    COMMIT;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/



GRANT GRANT ANY OBJECT PRIVILEGE TO webadmin;

GRANT GRANT ANY ROLE TO webAdmin;


GRANT CONNECT, RESOURCE, CREATE SESSION TO webAdmin;

GRANT CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO webAdmin;

GRANT UNLIMITED TABLESPACE TO webAdmin;

GRANT CREATE USER TO webAdmin;

GRANT DROP USER TO webAdmin;

GRANT CREATE ROLE TO webAdmin;

GRANT SELECT ON DBA_ROLES TO webAdmin;

GRANT CREATE SESSION TO webAdmin;

--GRANT ANY PRIVILEGE TO webAdmin WITH ADMIN OPTION;

